import os
from azure.identity import DefaultAzureCredential, AzureCliCredential, ManagedIdentityCredential, DeviceCodeCredential
from azure.mgmt.resource import ResourceManagementClient, SubscriptionClient
import logging


import requests

subscription_id = 'efdc416c-2887-4290-b3ff-f8ada95e2314'
URL = 'https://management.azure.com/subscriptions/' + subscription_id + '/resourcegroups?api-version=2021-04-01'
token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hOGNlYTBlOC0yZDVmLTQ3NzItOTQ0MC0yODIwYzBlZjQ0YjkvIiwiaWF0IjoxNjIyODIyMTUwLCJuYmYiOjE2MjI4MjIxNTAsImV4cCI6MTYyMjgyNjA1MCwiYWNyIjoiMSIsImFpbyI6IkFXUUFtLzhUQUFBQUJWcHpOaEZ0TU1oUGZEVWtCRWhIRUdxUWZsQmd1TkRDVzJKT2FycnBnT1g2MzBIdkU4Y1VyYWw3OEFPQ2xCcVRUQ1VxWXZjbnMrYm5tOHlUQUQ1Zk5pK0trUndQNG80YUo1L2d3WE9JNGZjSitPb092VTBQUERBRHRzWWdRN1hRIiwiYWx0c2VjaWQiOiIxOmxpdmUuY29tOjAwMDY0MDAwOTUxQTRBRUUiLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMDRiMDc3OTUtOGRkYi00NjFhLWJiZWUtMDJmOWUxYmY3YjQ2IiwiYXBwaWRhY3IiOiIwIiwiZW1haWwiOiJua3JldXR6YXJla0Bob3RtYWlsLmRlIiwiZmFtaWx5X25hbWUiOiJLcmV1dHphcmVrIiwiZ2l2ZW5fbmFtZSI6Ik5pa2xhcyIsImdyb3VwcyI6WyIwZjRjNzc5OC02NDlmLTQ2M2MtYWM3NS1iMDc2NmRmNDNkYjYiLCI5NWVjZjEyMi0yYTVkLTRiZGEtOTAzZC0wNmI2OTRmY2NmMTUiXSwiaWRwIjoibGl2ZS5jb20iLCJpcGFkZHIiOiI0Ni4yMjMuMTYzLjIxNiIsIm5hbWUiOiJOaWtsYXMgS3JldXR6YXJlayAobmtyZXV0emFyZWtAaG90bWFpbC5kZSkiLCJvaWQiOiIwYmZmZWRkYy05NGM4LTQzMzktYTM0NS0zZmZlMmMxNzMyOGUiLCJwdWlkIjoiMTAwMzIwMDEyRUE3MkI4RiIsInJoIjoiMC5BUjhBNktET3FGOHRja2VVUUNnZ3dPOUV1WlYzc0FUYmpScEd1LTRDLWVHX2UwWWZBS0kuIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiYTItZkNPXzYyeElTWTFJVkp0aEk2dF9qWXpxWTNvT2o2bkpTbnVJaC12cyIsInRpZCI6ImE4Y2VhMGU4LTJkNWYtNDc3Mi05NDQwLTI4MjBjMGVmNDRiOSIsInVuaXF1ZV9uYW1lIjoibGl2ZS5jb20jbmtyZXV0emFyZWtAaG90bWFpbC5kZSIsInV0aSI6IjZTTG8xUGdDODBpRUZPYjdQNjBUQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjEzYmQxYzcyLTZmNGEtNGRjZi05ODVmLTE4ZDNiODBmMjA4YSJdLCJ4bXNfdGNkdCI6MTQ4MTU2MjE1NX0.czaJRWxzz8LVBq7bhXXFMatN6jTqtPu9DQm1EyFuQ2cJRbyA289mWKNkRFGbXr0V6eN9wOoDuTUqOo7UWpPDKqJJ000Azc22HQVqFu2elu8mDUokNhGC01wbx5hpaJqoT46Ocs5Dp7MXOrkW4sXLcJpWuBLDMHniU43tdmFJ4Sx_CJkEuWZm28f717s12W8ZRbgsz7ovpZSuzwU9qd4_7bfjwG0uOYPxTZQUNxB62--1iBnbZtBhDykuVevyk519qLLucgk6cEFwxv2ISUllOCex_SgNJvf6SQ9bu--pCmErGdysI2OQvSk40P16eukTOT9OAW0mZTwyRoG6zQ5pZQ'
headers = {'Authorization': 'Bearer ' + token}
r = requests.get(URL, headers=headers)
print(r.json)
print(r.content)

""" logger = logging.getLogger(name='test')
handler = logging.StreamHandler()
formatter = logging.Formatter(
    '%(asctime)s [%(name)-12s] %(levelname)-8s %(message)s')
handler.setFormatter(formatter)
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)
logger.info("hello")
credentials = DeviceCodeCredential()
subscription_id = os.getenv('AZURE_SUBSCRIPTION_ID')
logger.info(subscription_id)
resource_client = ResourceManagementClient(credentials, subscription_id)
for resource_group in resource_client.resource_groups.list():
    logger.info(resource_group.name) """