apiVersion: v1
kind: Pod
metadata:
  name: app-demo
  namespace: default
  labels:
    aadpodidbinding: app-demo
spec:
  containers:
    - name: app-demo
      image: nickkr/azure_test:2.0
      env:
        - name:  RESOURCE_GROUP_NAME
          value: 'test-container'
        - name:  AZURE_SUBSCRIPTION_ID
          value: efdc416c-2887-4290-b3ff-f8ada95e2314
  nodeSelector:
    kubernetes.io/os: linux
